package shared.command;

public enum CommandType {
    HELP, INFO, SHOW, ADD, UPDATE, REMOVE_BY_ID, CLEAR,
    EXECUTE_SCRIPT, EXIT, REMOVE_FIRST, ADD_IF_MAX,
    HISTORY, MIN_BY_VENUE, FILTER_CONTAINS_NAME,
    PRINT_FIELD_DESCENDING_DISCOUNT, SERVER_SAVE, REGISTER
}